### ISSUE TITLE
Fraktal NFTs don't Transfer

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-UI#23]
URL

https://testnets.opensea.io/assets/0x91c734c665255855de8c1c46d73eb9e22ceaac75/0/transfer

Current
Giving error message and not triggering metamask. Saying it was declined but never popped up metamask.

Desired
Transfer NFTs to different addresses

Screenshot
<img width="1399" alt="Screen Shot 2021-08-27 at 19 59 50" src="https://user-images.githubusercontent.com/43958441/131170073-1948f4ab-a725-472a-ae5d-3e3346f52ad7.png">

**Comment by cryptnotiq** [comment]
@earth2travis this one isn't working still.

Current
When you mint an NFT on Fraktal it does not show up on Opensea
When you lock the NFT it does show up on Opensea but still is not transferrable
When you fraktionlise it, you can transfer the fraktions via opensea to another metamask account, BUT when you try to transfer to a DAO minion vault (i.e 0x6617ae26a9468c30b05e406a825f45acf37a6f58) it does not transfer and gives an error message.

**Comment by earth2travis** [comment]
Please see comment from @cryptnotiq above

**Comment by earth2travis** [comment]
Mint NFT receive fractions. Have to defractionalize to move it around.  Run into complex interactions. NFT and could not send it out because it was not locked. The contracts have been added to say if the token has been fractionalized it is it is locked. If it has an offer of over 80% it can be sold.
